services:
  cut-tube-api:
    build:
      context: ./cut-tube-api
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./cut-tube-api/.env
    volumes:
      - ./cut-tube-api:/home/app
      - /home/app/venv
      - /home/app/.pytest_cache
      - /home/app/.ruff_cache
      - /home/app/.mypy_cache
      - /home/app/__pycache__
    ports:
      - 5050:5050
    networks:
      - cut-tube-net

  cut-tube-app:
    build:
      context: ./cut-tube-app
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./cut-tube-app/.env
    volumes:
      - ./cut-tube-app:/home/app
      - /home/app/node_modules
    depends_on:
      - cut-tube-api
    ports:
      - "3000:3000"
    networks:
      - cut-tube-net
    stdin_open: true
    tty: true

networks:
  cut-tube-net:
