services:
  cut-tube-app:
    build:
      context: ./cut-tube-app
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:8080
    env_file:
      - ./cut-tube-app/.env
    networks:
      - net-cut-tube
    depends_on:
      - cut-tube-api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  cut-tube-api:
    build:
      context: ./cut-tube-api
      dockerfile: Dockerfile.production
    restart: always
    expose:
      - 5050:5050
    env_file: ./cut-tube-api/.env
    networks:
      - net-cut-tube

networks:
  net-cut-tube:
    name: net-cut-tube
