# ##### SUCCESS #####
CODE_SUCCESS_CUT_VIDEO = "SUCCESS_CUT_VIDEO"
CODE_SUCCESS_DELETE_CLIP = "SUCCESS_DELETE_CLIP"

# ##### ERROR #####
CODE_ERROR_INTERNAL_SERVER = "ERROR_INTERNAL_SERVER"
CODE_ERROR_PYDANTIC = "ERROR_PYDANTIC"
CODE_ERROR_GENERIC = "ERROR_GENERIC"
CODE_ERROR_VIDEO_TUBE_SERVICE = "ERROR_VIDEO_TUBE_SERVICE"

# ##### NOT #####

# ##### NOT_VALID #####
CODE_NOT_VALID_FIELDS = "NOT_VALID_FIELDS"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####

# ##### NOT_FOUND #####
CODE_NOT_FOUND_PATH = "NOT_FOUND_PATH"
