repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
      
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
        args: [--config-file=cut-tube-api/pyproject.toml, cut-tube-api]
        pass_filenames: false
        exclude: ^(cut-tube-api/tests/|cut-tube-api/venv/)